DATA CLEANING

In [47]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# MY DATASETS.
This project has four datasets of every registered health facility in kenya, both public and private
1. health_units.csv
2. hispital_beds.csv
3. hospitals_and_beds.csv
4. pharmacies.csv

# Cleaning Steps
1. Load data.
2. Preview and understand the data.
3. Handle missing values and duplicates
4. Fix data types 
5. Standardise values and categories

In [48]:
def clean_data():




    return data

In [49]:
#Load Dataset
health_units = pd.read_csv("../data/raw/health_units.csv")
health_units.head()

,Status,Facility,Facility_ward,Facility_constituency,Facility_subcounty,Facility_county,Name,Code,Date_established
0,Fully-functional,Nadanya Dispensary,Lyaduywa/Izava,Sabatia,Sabatia,Vihiga,Mukingi Community Unit,703403,41792
1,Fully-functional,Kegondi Health Centre,West Sabatia,Sabatia,Sabatia,Vihiga,Hamuyundi Community Unit,703415,41074
2,Fully-functional,Kegondi Health Centre,West Sabatia,Sabatia,Sabatia,Vihiga,Solongo Community Unit,703416,41974
3,Fully-functional,Givudimbuli Health Centre,Wodanga,Sabatia,Sabatia,Vihiga,Gaigedi Community Unit,703417,41703
4,Fully-functional,Givudimbuli Health Centre,Wodanga,Sabatia,Sabatia,Vihiga,Gaigedi,703418,41703

In [50]:
#Load Dataset Two
hospital_beds = pd.read_csv("../data/raw/hospital_beds.csv")
hospital_beds.head()

         Geography  Number of hospital beds
0          Baringo                      820
1            Bomet                      845
2          Bungoma                     2038
3            Busia                     1314
4  Elgeyo-Marakwet                      858

In [51]:
#Load Dataset Three
hospital_n_beds = pd.read_csv("../data/raw/hospitals_and_beds.csv")
hospital_n_beds.head()

,Code,Name,Officialname,Registration_number,Keph level,Facility type,Facility_type_category,Owner,Owner type,Regulatory body,...,Ward,Operation status,Open_whole_day,Open_public_holidays,Open_weekends,Open_late_night,Service_names,Approved,Public visible,Closed
0,25720.0,Itete Dispensary,Itete Dispensary,01245,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Koyonzo,Operational,No,No,No,No,NaN,Yes,Yes,No
1,25722.0,Penda Medical Center - Mathare North,Penda Medical Center - Mathare North,017345,Level 3,Medical Center,MEDICAL CENTER,Private Practice - Private Company,Private Practice,Kenya MPDB,...,Mathare North,Operational,No,Yes,Yes,No,NaN,Yes,Yes,No
2,NaN,Mukavakava,Mukavakava,NaN,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Butali/Chegulo,Operational,No,No,No,No,NaN,Yes,Yes,No
3,NaN,Nchurra Dispensary,Nchurra Dispensary,NaN,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Melelo,Operational,No,No,No,No,NaN,Yes,Yes,No
4,NaN,Upland Health Care Center,Upland Health Care Center,NaN,Level 2,Medical Clinic,MEDICAL CLINIC,Private Practice - Nurse / Midwifery,Private Practice,NaN,...,Kerugoya,Operational,No,Yes,Yes,Yes,NaN,Yes,Yes,No

In [52]:
#Load Dataset Four
pharmacies = pd.read_csv("../data/raw/pharmacies.csv")
pharmacies.head()

,Code,Name,Officialname,Registration_number,Keph level,Facility type,Facility_type_category,Owner,Owner type,Regulatory body,...,Ward,Operation status,Open_whole_day,Open_public_holidays,Open_weekends,Open_late_night,Service_names,Approved,Public visible,Closed
0,25720.0,Itete Dispensary,Itete Dispensary,01245,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Koyonzo,Operational,No,No,No,No,NaN,Yes,Yes,No
1,NaN,Mukavakava,Mukavakava,NaN,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Butali/Chegulo,Operational,No,No,No,No,NaN,Yes,Yes,No
2,NaN,Nchurra Dispensary,Nchurra Dispensary,NaN,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Melelo,Operational,No,No,No,No,NaN,Yes,Yes,No
3,25716.0,Kitaor Dispensary,Kitaor Dispensary,26121,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Kemeloi-maraba,Operational,No,No,No,No,NaN,Yes,Yes,No
4,25697.0,Emaira Dispensary,Emaira Dispensary,NaN,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,NaN,...,Marama West,Operational,No,No,No,No,NaN,Yes,Yes,No

In [53]:
#Check the shape of all datasets
print("healthunits: " ,health_units.shape)
print("hospital_beds: " ,hospital_beds.shape)
print("hospital_n_beds" ,hospital_n_beds.shape)
print("pharmacies: " ,pharmacies.shape)

healthunits:  (5558, 9)
hospital_beds:  (48, 2)
hospital_n_beds (12394, 26)
pharmacies:  (5219, 26)

# Inspect the Health Units data.

In [ ]:


print("Shape of health_units: " ,health_units.shape)
print("MIssing values: ", health_units.isnull().sum())
print("Health units unique values: ", health_units["Status"].value_counts())

Shape of health_units:  (5558, 9)
MIssing values:  Status                   0
Facility                 0
Facility_ward            0
Facility_constituency    0
Facility_subcounty       0
Facility_county          0
Name                     0
Code                     0
Date_established         0
dtype: int64
Health units unique values:  Status
Fully-functional    3686
semi-functional     1490
non-functinoal       268
Closed               114
Name: count, dtype: int64

The code that checks the unique values of the status of health units had "non-functinoal" which is a typo
THis indicates that there is data that is wrongly labelled. 
Also, non-functinoal and closed are the same. So the rows that have "non-functinoal" as a status will be turned to Closed.

In [67]:
health_units["Status"] = health_units['Status'].str.replace('non-functinoal', 'Closed')
health_units['Status'].value_counts()

Status
Fully-functional    3686
semi-functional     1490
Closed               382
Name: count, dtype: int64

In [55]:
#Inspect the dates of Date_established that look sketchy 
print(health_units['Date_established'].head(20).tolist())

[41792, 41074, 41974, 41703, 41703, 43878, 43889, 43529, 43850, 43836, 42618, 41519, 41701, 41701, 41701, 41701, 41701, 41701, 41701, 41701]

In [56]:
#See the max and min value of Date_established 
print('\nMin value:', health_units['Date_established'].min())
print('Max value:', health_units['Date_established'].max())

Min value: 2005
Max value: 43889

The Date_established column has data in number of days as from 1st January 1900 contrary to date time data that is required
Convert it to year_established and drop date, Year_established ans Date_established.

In [ ]:
health_units['date'] = pd.to_datetime(health_units['Date_established'], origin='1899-12-30', unit='D')
health_units['year'] = health_units['date'].dt.year
health_units.drop(['Date_established', 'Year_established', 'date'], axis=1, inplace = True)
health_units.head()

,Status,Facility,Facility_ward,Facility_constituency,Facility_subcounty,Facility_county,Name,Code,Date_established,date,year
0,Fully-functional,Nadanya Dispensary,Lyaduywa/Izava,Sabatia,Sabatia,Vihiga,Mukingi Community Unit,703403,41792,2014-06-02,2014
1,Fully-functional,Kegondi Health Centre,West Sabatia,Sabatia,Sabatia,Vihiga,Hamuyundi Community Unit,703415,41074,2012-06-14,2012
2,Fully-functional,Kegondi Health Centre,West Sabatia,Sabatia,Sabatia,Vihiga,Solongo Community Unit,703416,41974,2014-12-01,2014
3,Fully-functional,Givudimbuli Health Centre,Wodanga,Sabatia,Sabatia,Vihiga,Gaigedi Community Unit,703417,41703,2014-03-05,2014
4,Fully-functional,Givudimbuli Health Centre,Wodanga,Sabatia,Sabatia,Vihiga,Gaigedi,703418,41703,2014-03-05,2014

In [87]:
#Check for typos in Counties to avoid duplicates
(health_units["Facility_county"].to_string())

'0                Vihiga\n1                Vihiga\n2                Vihiga\n3                Vihiga\n4                Vihiga\n5               Makueni\n6               Makueni\n7                  Lamu\n8                  Meru\n9                  Meru\n10                 Lamu\n11                 Lamu\n12                Kisii\n13                Kisii\n14                Kisii\n15                Kisii\n16                Kisii\n17                Kisii\n18                Kisii\n19                Kisii\n20                Kisii\n21                Kisii\n22                Kisii\n23                Kisii\n24               Vihiga\n25               Vihiga\n26               Vihiga\n27               Vihiga\n28               Vihiga\n29               Vihiga\n30               Vihiga\n31               Vihiga\n32               Vihiga\n33               Vihiga\n34               Vihiga\n35               Vihiga\n36               Vihiga\n37               Vihiga\n38               Vihiga\n39               Vihiga\n40               Vihiga\n41               Vihiga\n42               Vihiga\n43               Vihiga\n44               Vihiga\n45               Vihiga\n46               Vihiga\n47               Vihiga\n48               Vihiga\n49               Vihiga\n50               Vihiga\n51               Vihiga\n52               Vihiga\n53               Vihiga\n54           Tana River\n55           Tana River\n56               Vihiga\n57               Vihiga\n58               Vihiga\n59               Vihiga\n60                 Lamu\n61               Vihiga\n62               Vihiga\n63               Vihiga\n64               Vihiga\n65               Vihiga\n66             Homa Bay\n67                 Lamu\n68               Vihiga\n69               Vihiga\n70                 Meru\n71                 Meru\n72                 Meru\n73                 Meru\n74                 Meru\n75                 Meru\n76                 Meru\n77                 Meru\n78                 Meru\n79                 Meru\n80                 Meru\n81                 Meru\n82                Nyeri\n83              Mombasa\n84             Marsabit\n85              Kajiado\n86              Kajiado\n87              Kajiado\n88              Kajiado\n89              Kajiado\n90              Kajiado\n91              Kajiado\n92              Kajiado\n93                Nyeri\n94                Nyeri\n95              Kajiado\n96             Machakos\n97             Machakos\n98            Kirinyaga\n99             Kakamega\n100             Kericho\n101             Kericho\n102             Mandera\n103              Isiolo\n104              Isiolo\n105              Isiolo\n106              Isiolo\n107              Isiolo\n108            Machakos\n109         Uasin Gishu\n110                Meru\n111               Busia\n112               Busia\n113               Busia\n114               Busia\n115               Busia\n116            Homa Bay\n117            Homa Bay\n118            Homa Bay\n119            Homa Bay\n120            Homa Bay\n121            Homa Bay\n122            Homa Bay\n123            Homa Bay\n124            Homa Bay\n125            Homa Bay\n126            Homa Bay\n127            Homa Bay\n128            Homa Bay\n129            Homa Bay\n130            Homa Bay\n131            Homa Bay\n132            Homa Bay\n133            Homa Bay\n134            Homa Bay\n135            Homa Bay\n136            Homa Bay\n137            Homa Bay\n138            Homa Bay\n139            Homa Bay\n140            Homa Bay\n141            Homa Bay\n142            Homa Bay\n143            Homa Bay\n144            Homa Bay\n145            Homa Bay\n146            Homa Bay\n147            Homa Bay\n148            Homa Bay\n149            Homa Bay\n150            Homa Bay\n151              Migori\n152              Migori\n153              Migori\n154              Migori\n155              Migori\n156              Migori\n157              Migori\n158              Migori\n159              Migori\n160              Migori\n161              Migori\n162              Migori\n163              Migori\n164              Migori\n165              Migori\n166            Homa Bay\n167            Homa Bay\n168            Homa Bay\n169            Homa Bay\n170            Homa Bay\n171            Homa Bay\n172            Homa Bay\n173            Homa Bay\n174            Homa Bay\n175            Homa Bay\n176            Homa Bay\n177             Kajiado\n178             Kajiado\n179             Kajiado\n180             Kajiado\n181             Kajiado\n182             Kajiado\n183             Kajiado\n184             Kajiado\n185             Kajiado\n186             Kajiado\n187             Kajiado\n188             Kajiado\n189             Kajiado\n190             Kajiado\n191             Kajiado\n192             Kajiado\n193             Kajiado\n194             Kajiado\n195             Kajiado\n196             Kajiado\n197             Kajiado\n198             Kajiado\n199             Kajiado\n200             Kajiado\n201             Kajiado\n202             Kajiado\n203             Kajiado\n204             Kajiado\n205             Kajiado\n206             Kajiado\n207             Kajiado\n208             Kajiado\n209             Kajiado\n210             Kajiado\n211             Kajiado\n212            Machakos\n213            Machakos\n214            Machakos\n215            Machakos\n216            Machakos\n217            Machakos\n218            Machakos\n219     Elgeyo Marakwet\n220            Homa Bay\n221            Homa Bay\n222            Homa Bay\n223            Homa Bay\n224            Homa Bay\n225            Homa Bay\n226              Kiambu\n227              Kiambu\n228              Kiambu\n229              Kiambu\n230              Kiambu\n231              Kiambu\n232              Kiambu\n233              Kiambu\n234              Kiambu\n235              Kiambu\n236              Kiambu\n237              Kiambu\n238              Kiambu\n239              Kiambu\n240              Kiambu\n241              Kiambu\n242              Kiambu\n243              Kiambu\n244              Kiambu\n245              Kiambu\n246              Kiambu\n247              Kiambu\n248              Kiambu\n249              Kiambu\n250              Kiambu\n251              Kiambu\n252              Kiambu\n253              Kiambu\n254              Kiambu\n255              Kiambu\n256              Kiambu\n257              Kiambu\n258              Kiambu\n259              Kiambu\n260              Kiambu\n261              Kiambu\n262              Kiambu\n263              Kiambu\n264              Kiambu\n265              Kiambu\n266              Kiambu\n267              Kiambu\n268              Kiambu\n269              Kiambu\n270              Kiambu\n271              Kiambu\n272              Kiambu\n273              Kiambu\n274              Kisumu\n275              Kisumu\n276              Kisumu\n277              Kisumu\n278              Kisumu\n279              Kisumu\n280              Kisumu\n281              Kisumu\n282              Kisumu\n283              Kisumu\n284              Kisumu\n285              Kisumu\n286              Kisumu\n287              Kiambu\n288              Kiambu\n289              Kisumu\n290              Kiambu\n291              Kisumu\n292              Kiambu\n293              Kiambu\n294              Kiambu\n295              Kiambu\n296              Kiambu\n297              Kiambu\n298              Kiambu\n299              Kiambu\n300              Kiambu\n301              Kiambu\n302            Homa Bay\n303            Homa Bay\n304              Kiambu\n305              Kiambu\n306              Kiambu\n307              Kiambu\n308              Kiambu\n309              Kiambu\n310              Kiambu\n311              Kiambu\n312              Kiambu\n313              Kiambu\n314              Kiambu\n315            Homa Bay\n316            Homa Bay\n317            Homa Bay\n318            Homa Bay\n319              Kiambu\n320               Siaya\n321              Kiambu\n322            Homa Bay\n323            Homa Bay\n324            Homa Bay\n325            Homa Bay\n326            Homa Bay\n327            Homa Bay\n328            Homa Bay\n329            Homa Bay\n330            Homa Bay\n331            Homa Bay\n332            Homa Bay\n333            Homa Bay\n334            Homa Bay\n335             Samburu\n336             Samburu\n337             Samburu\n338             Samburu\n339            Machakos\n340            Machakos\n341              Kiambu\n342            Machakos\n343            Machakos\n344            Machakos\n345            Machakos\n346            Machakos\n347            Machakos\n348            Machakos\n349            Machakos\n350            Machakos\n351            Machakos\n352            Machakos\n353            Machakos\n354            Machakos\n355            Machakos\n356            Machakos\n357            Machakos\n358            Machakos\n359            Machakos\n360            Machakos\n361            Machakos\n362            Machakos\n363            Machakos\n364            Machakos\n365            Machakos\n366            Machakos\n367            Machakos\n368            Machakos\n369            Machakos\n370            Machakos\n371            Machakos\n372            Machakos\n373            Machakos\n374            Machakos\n375            Machakos\n376            Machakos\n377            Machakos\n378            Machakos\n379            Machakos\n380             Kajiado\n381             Kajiado\n382            Machakos\n383            Machakos\n384            Machakos\n385            Machakos\n386            Machakos\n387            Machakos\n388            Machakos\n389            Machakos\n390            Machakos\n391            Machakos\n392            Machakos\n393            Machakos\n394               Kisii\n395               Kisii\n396               Kisii\n397               Kisii\n398               Kisii\n399               Kisii\n400               Kisii\n401               Kisii\n402               Kisii\n403               Kisii\n404               Kisii\n405               Kisii\n406               Kisii\n407               Kisii\n408            Machakos\n409            Machakos\n410            Machakos\n411            Machakos\n412            Machakos\n413            Machakos\n414            Machakos\n415            Machakos\n416            Machakos\n417            Machakos\n418            Machakos\n419            Machakos\n420            Machakos\n421            Machakos\n422            Machakos\n423            Machakos\n424            Machakos\n425            Machakos\n426            Machakos\n427            Machakos\n428            Machakos\n429            Machakos\n430            Machakos\n431            Machakos\n432            Machakos\n433            Machakos\n434            Machakos\n435            Machakos\n436            Machakos\n437            Machakos\n438            Machakos\n439            Machakos\n440            Machakos\n441            Machakos\n442            Machakos\n443            Machakos\n444            Machakos\n445            Machakos\n446            Machakos\n447            Machakos\n448            Machakos\n449            Machakos\n450            Machakos\n451            Machakos\n452            Machakos\n453            Machakos\n454            Machakos\n455            Machakos\n456            Machakos\n457              Kilifi\n458              Kilifi\n459              Kilifi\n460              Kilifi\n461           Kirinyaga\n462           Kirinyaga\n463           Kirinyaga\n464              Kisumu\n465              Kisumu\n466              Kisumu\n467              Kisumu\n468              Kisumu\n469               Bomet\n470             Turkana\n471             Turkana\n472             Turkana\n473             Turkana\n474             Turkana\n475             Turkana\n476             Turkana\n477             Turkana\n478             Turkana\n479             Turkana\n480       Tharaka Nithi\n481       Tharaka Nithi\n482       Tharaka Nithi\n483       Tharaka Nithi\n484       Tharaka Nithi\n485       Tharaka Nithi\n486       Tharaka Nithi\n487              Migori\n488             Makueni\n489       Tharaka Nithi\n490       Tharaka Nithi\n491       Tharaka Nithi\n492       Tharaka Nithi\n493       Tharaka Nithi\n494       Tharaka Nithi\n495       Tharaka Nithi\n496       Tharaka Nithi\n497       Tharaka Nithi\n498       Tharaka Nithi\n499       Tharaka Nithi\n500               Kwale\n501               Kwale\n502               Kwale\n503               Kwale\n504               Kwale\n505               Kwale\n506               Kwale\n507               Kwale\n508               Kwale\n509       Tharaka Nithi\n510       Tharaka Nithi\n511       Tharaka Nithi\n512       Tharaka Nithi\n513       Tharaka Nithi\n514       Tharaka Nithi\n515       Tharaka Nithi\n516       Tharaka Nithi\n517       Tharaka Nithi\n518       Tharaka Nithi\n519       Tharaka Nithi\n520       Tharaka Nithi\n521       Tharaka Nithi\n522       Tharaka Nithi\n523       Tharaka Nithi\n524       Tharaka Nithi\n525       Tharaka Nithi\n526       Tharaka Nithi\n527       Tharaka Nithi\n528       Tharaka Nithi\n529       Tharaka Nithi\n530       Tharaka Nithi\n531       Tharaka Nithi\n532       Tharaka Nithi\n533       Tharaka Nithi\n534       Tharaka Nithi\n535       Tharaka Nithi\n536       Tharaka Nithi\n537       Tharaka Nithi\n538       Tharaka Nithi\n539       Tharaka Nithi\n540       Tharaka Nithi\n541       Tharaka Nithi\n542       Tharaka Nithi\n543       Tharaka Nithi\n544       Tharaka Nithi\n545       Tharaka Nithi\n546       Tharaka Nithi\n547       Tharaka Nithi\n548       Tharaka Nithi\n549       Tharaka Nithi\n550       Tharaka Nithi\n551       Tharaka Nithi\n552       Tharaka Nithi\n553       Tharaka Nithi\n554       Tharaka Nithi\n555       Tharaka Nithi\n556       Tharaka Nithi\n557       Tharaka Nithi\n558       Tharaka Nithi\n559       Tharaka Nithi\n560       Tharaka Nithi\n561               Bomet\n562         Uasin Gishu\n563         Uasin Gishu\n564                Meru\n565                Meru\n566                Meru\n567                Meru\n568                Meru\n569                Meru\n570                Meru\n571                Meru\n572                Meru\n573                Meru\n574                Meru\n575         Uasin Gishu\n576         Uasin Gishu\n577         Uasin Gishu\n578         Uasin Gishu\n579         Uasin Gishu\n580         Uasin Gishu\n581         Uasin Gishu\n582         Uasin Gishu\n583         Uasin Gishu\n584         Uasin Gishu\n585         Uasin Gishu\n586         Uasin Gishu\n587         Uasin Gishu\n588         Uasin Gishu\n589         Uasin Gishu\n590         Uasin Gishu\n591         Uasin Gishu\n592         Uasin Gishu\n593         Uasin Gishu\n594         Uasin Gishu\n595                Meru\n596                Meru\n597                Meru\n598         Uasin Gishu\n599         Uasin Gishu\n600         Uasin Gishu\n601         Uasin Gishu\n602         Uasin Gishu\n603         Uasin Gishu\n604         Uasin Gishu\n605               Bomet\n606         Uasin Gishu\n607         Uasin Gishu\n608         Uasin Gishu\n609         Uasin Gishu\n610         Uasin Gishu\n611         Uasin Gishu\n612         Uasin Gishu\n613         Uasin Gishu\n614         Uasin Gishu\n615         Uasin Gishu\n616         Uasin Gishu\n617         Uasin Gishu\n618         Uasin Gishu\n619         Uasin Gishu\n620         Uasin Gishu\n621             Makueni\n622                Meru\n623                Meru\n624         Uasin Gishu\n625         Uasin Gishu\n626         Uasin Gishu\n627         Uasin Gishu\n628         Uasin Gishu\n629         Uasin Gishu\n630         Uasin Gishu\n631         Uasin Gishu\n632         Uasin Gishu\n633         Uasin Gishu\n634         Uasin Gishu\n635         Uasin Gishu\n636         Uasin Gishu\n637         Uasin Gishu\n638         Uasin Gishu\n639         Uasin Gishu\n640         Uasin Gishu\n641         Uasin Gishu\n642         Uasin Gishu\n643         Uasin Gishu\n644         Uasin Gishu\n645         Uasin Gishu\n646         Uasin Gishu\n647         Uasin Gishu\n648         Uasin Gishu\n649         Uasin Gishu\n650         Uasin Gishu\n651               Nyeri\n652               Nyeri\n653               Nyeri\n654               Nyeri\n655             Makueni\n656              Kilifi\n657              Kilifi\n658              Kilifi\n659              Kilifi\n660              Kilifi\n661              Kilifi\n662              Kilifi\n663               Bomet\n664               Bomet\n665               Bomet\n666               Bomet\n667               Bomet\n668               Bomet\n669               Bomet\n670               Bomet\n671               Bomet\n672               Bomet\n673               Bomet\n674               Bomet\n675               Bomet\n676               Bomet\n677               Bomet\n678               Bomet\n679              Kiambu\n680              Kiambu\n681              Kiambu\n682              Kiambu\n683             Makueni\n684             Makueni\n685             Makueni\n686             Makueni\n687             Makueni\n688               Bomet\n689               Bomet\n690               Bomet\n691               Bomet\n692               Bomet\n693               Bomet\n694               Bomet\n695               Bomet\n696               Bomet\n697               Bomet\n698               Bomet\n699               Bomet\n700               Bomet\n701               Bomet\n702               Bomet\n703               Bomet\n704               Bomet\n705               Bomet\n706               Bomet\n707               Bomet\n708               Bomet\n709               Bomet\n710               Bomet\n711               Bomet\n712               Bomet\n713               Bomet\n714               Bomet\n715               Bomet\n716               Bomet\n717               Bomet\n718               Bomet\n719               Bomet\n720               Bomet\n721               Bomet\n722               Bomet\n723               Bomet\n724               Bomet\n725               Bomet\n726               Bomet\n727               Bomet\n728               Bomet\n729               Bomet\n730               Bomet\n731               Bomet\n732               Bomet\n733               Bomet\n734               Bomet\n735               Bomet\n736               Bomet\n737               Bomet\n738               Bomet\n739               Bomet\n740               Bomet\n741               Bomet\n742               Bomet\n743               Bomet\n744               Bomet\n745               Bomet\n746               Bomet\n747               Bomet\n748               Bomet\n749               Bomet\n750               Bomet\n751               Bomet\n752               Bomet\n753               Bomet\n754               Bomet\n755               Bomet\n756               Bomet\n757               Bomet\n758               Bomet\n759               Bomet\n760               Bomet\n761               Bomet\n762               Bomet\n763               Bomet\n764               Bomet\n765               Bomet\n766               Bomet\n767               Bomet\n768              Migori\n769              Migori\n770              Migori\n771              Migori\n772              Migori\n773          Tana River\n774          Tana River\n775             Kericho\n776              Kisumu\n777              Kisumu\n778              Kisumu\n779              Kisumu\n780              Kisumu\n781              Kisumu\n782                Meru\n783                Meru\n784                Meru\n785                Meru\n786            Kakamega\n787               Busia\n788               Busia\n789               Busia\n790               Busia\n791               Busia\n792               Busia\n793               Busia\n794               Busia\n795               Busia\n796               Busia\n797               Busia\n798               Busia\n799               Busia\

# Inspect Pharmacies Data

In [89]:
pharmacies.head()

,Code,Name,Officialname,Registration_number,Keph level,Facility type,Facility_type_category,Owner,Owner type,Regulatory body,...,Ward,Operation status,Open_whole_day,Open_public_holidays,Open_weekends,Open_late_night,Service_names,Approved,Public visible,Closed
0,25720.0,Itete Dispensary,Itete Dispensary,01245,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Koyonzo,Operational,No,No,No,No,NaN,Yes,Yes,No
1,NaN,Mukavakava,Mukavakava,NaN,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Butali/Chegulo,Operational,No,No,No,No,NaN,Yes,Yes,No
2,NaN,Nchurra Dispensary,Nchurra Dispensary,NaN,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Melelo,Operational,No,No,No,No,NaN,Yes,Yes,No
3,25716.0,Kitaor Dispensary,Kitaor Dispensary,26121,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,Ministry of Health,...,Kemeloi-maraba,Operational,No,No,No,No,NaN,Yes,Yes,No
4,25697.0,Emaira Dispensary,Emaira Dispensary,NaN,Level 2,Dispensary,DISPENSARY,Ministry of Health,Ministry of Health,NaN,...,Marama West,Operational,No,No,No,No,NaN,Yes,Yes,No

In [95]:
# Check shape, missing values unique values
print("shape of Pharmacies dataset: " ,pharmacies.shape)
print("Missing values: ", pharmacies.isnull().sum())
print("UNique values: " ,pharmacies["Regulatory body"].value_counts())

shape of Pharmacies dataset:  (5219, 26)
Missing values:  Code                         9
Name                         0
Officialname                 0
Registration_number       5064
Keph level                   0
Facility type                0
Facility_type_category       0
Owner                        0
Owner type                   0
Regulatory body            300
Beds                         0
Cots                         0
Beds and Cots                0
County                       0
Constituency                 0
Sub county                   0
Ward                         0
Operation status             0
Open_whole_day               0
Open_public_holidays         0
Open_weekends                0
Open_late_night              0
Service_names             5219
Approved                     0
Public visible               0
Closed                       0
dtype: int64
UNique values:  Regulatory body
Ministry of Health                                      3969
Kenya MPDB                                               863
Nursing Council of Kenya (Private Practice)               37
Clinical Officers Council                                 15
Other                                                     14
Pharmacy & Poisons Board                                  13
Kenya Medical Laboratory, Tech & Technologists Board       3
Kenya MPDB - Private Practice (deleted)                    3
Kenya Nuclear Regulatory Council ( Radiation Board)        2
Name: count, dtype: int64

In [96]:
pharmacies["Regulatory body"].value_counts()

Regulatory body
Ministry of Health                                      3969
Kenya MPDB                                               863
Nursing Council of Kenya (Private Practice)               37
Clinical Officers Council                                 15
Other                                                     14
Pharmacy & Poisons Board                                  13
Kenya Medical Laboratory, Tech & Technologists Board       3
Kenya MPDB - Private Practice (deleted)                    3
Kenya Nuclear Regulatory Council ( Radiation Board)        2
Name: count, dtype: int64

Pharmacies Data Set cleaning steps
1. Drop one